### ISSUE TITLE
no 'Initiate_Hummus_Object' function

### ISSUE THREAD

**Issue by ofircohn** [cantinilab/HuMMuS#5]
Hi!
Don't forget to add this part haha :)
hummus_object function results in ' no method for coercing this S4 class to a vector'.

**Comment by ofircohn** [comment]
Hey!
Great! Now it works!
One question - How do you focus on a subset/cell type/cluster? Do you subset it before or after running the pipeline? If after, then how do you extract it?

Thank you!

**Comment by r-trimbour** [comment]
Hi,

It's actually not a so trivial question :)

In the paper, we have built both cell-type specific networks, and GRN common to several cell-types.

My recommendation would be to divide your dataset by cell-types for the beginning if you're interested into comparing individual regulatory links (e.g. compare top enhancers, top target genes, etc) or the overall network structure.

But if you want to find the TF that might drive your cell's identity, then the consensus is usually to infer the network for all your data at the same time. Then you can calculate cell-type TF activity from the output GRN. It's recommended because keeping enough variability in your data (e.g. by having different cell types), help to denoise the predictions.

**Comment by ofircohn** [comment]
Hey !
I will try both! 
Last question - 
For the seconds option, how do you define cell-type specific TF ? by using DAR? Mean expression? motif activity?. 

Thank you!

**Comment by r-trimbour** [comment]
Hi @ofircohn ,

For the cell-type specific TF, I'm doing it through TF activity, they differential expression usually yes.
You can check https://github.com/saezlab/decoupleR for a nice package to do so, there is also a python version.



Rémi
